#
# This is the name (without extension) of the project to be built.
#

PROJECT = tetris

#
# These are the names (with extensions) of the files that are included
# by the PROJECT, and that need to be built.
#

INCLUDES = tetlcd.hlp tetcrt.hlp

#
# If there are any INCLUDES that have to be built with a special
# program, put those rules here, following the "all" rule.
#

all: $(PROJECT)

!INCLUDE ..\..\makefile\makefile.inc